config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "home#index"

  resources :beers
  resources :countries
  resources :styles
  resources :breweries

  #resources :users, only: [:new, :create, :show]
	resource :session, only: [:new, :create, :destroy]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/beer.rb
class Beer < ApplicationRecord
	belongs_to :brewery
	belongs_to :country
	belongs_to :style

	#has_attached_file :image, styles: { large: "450x450>", medium: "250x250>", thumb: "50x50>" }
  #validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/models/brewery.rb
class Brewery < ApplicationRecord
	has_many :beers
end

app/models/country.rb
class Country < ApplicationRecord
	has_many :beers

	#has_attached_file :image, styles: { large: "400x400>", medium: "250x250>", thumb: "25x25#" }
  #validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/models/style.rb
class Style < ApplicationRecord
	has_many :beers	
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  validates_presence_of :username

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def current_user
   	@current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :current_user

  def logged_in?
    current_user
  end

  helper_method :logged_in?

  protected

  def authorize
  	redirect_to new_session_path unless current_user  	
  end
end

app/controllers/beers_controller.rb
class BeersController < ApplicationController
	before_action :authorize, { only: [:new, :update, :destroy, :edit] }
	before_action :find_beer, { only: [:edit, :update, :show, :destroy] }

	def index
		@beers = Beer.all.paginate(:page => params[:page], :per_page => 10)
	end

  def new
		@beer = Beer.new
	end

	def create
		@beer = Beer.new(beer_params)

		if @beer.save
			flash[:notice] = 'Beer created succesfully :)'
			redirect_to beers_path
		else
			render :new
		end

	end

	def edit
			
	end

	def update		
	  
		if @beer.update(beer_params)
			redirect_to @beer
		else
			render :edit
		end
	end

	def show    
    #@products = @seller.products
  end

	def destroy
	
		@beer.destroy
		flash[:notice] = 'Beer deleted succesfully'
		redirect_to beers_path
	end

	private 

	def beer_params
		params.require(:beer).permit(:name, :quantity, :country_id, :style_id, :brewery_id, :image)
	end
  
  def find_beer
		@beer = Beer.find(params[:id])
	end

end

app/controllers/breweries_controller.rb
class BreweriesController < ApplicationController
	before_action :authorize, { only: [:new, :update, :destroy, :edit] }
	before_action :find_brewery, { only: [:edit, :update, :show, :destroy] }

	def index
		@breweries = Brewery.all.paginate(:page => params[:page], :per_page => 10)
	end

  def new
		@brewery = Brewery.new
	end

	def create
		@brewery = Brewery.new(brewery_params)

		if @brewery.save
			flash[:notice] = 'Brewery created succesfully :)'
			redirect_to breweries_path
		else
			render :new
		end

	end

	def edit
			
	end

	def update		
	  
		if @brewery.update(brewery_params)
			redirect_to @brewery
		else
			render :edit
		end
	end

	def show    
    @beers = @brewery.beers
  end

	def destroy
	
		@brewery.destroy
		flash[:notice] = 'Brewery deleted succesfully'
		redirect_to breweries_path
	end

	private 

	def brewery_params
		params.require(:brewery).permit(:name, :image)
	end
  
  def find_brewery
		@brewery = Brewery.find(params[:id])
	end
end

app/controllers/countries_controller.rb
class CountriesController < ApplicationController
	before_action :authorize, { only: [:new, :update, :destroy, :edit] }
	before_action :find_country, { only: [:edit, :update, :show, :destroy] }

	def index
		@countries = Country.all.paginate(:page => params[:page], :per_page => 10)
	end

  def new
		@country = Country.new
	end

	def create
		@country = Country.new(country_params)

		if @country.save
			flash[:notice] = 'Country created succesfully :)'
			redirect_to countries_path
		else
			render :new
		end

	end

	def edit
			
	end

	def update		
	  
		if @country.update(country_params)
			redirect_to @country
		else
			render :edit
		end
	end

	def show    
    @beers = @country.beers
  end

	def destroy
	
		@country.destroy
		flash[:notice] = 'Country deleted succesfully'
		redirect_to countries_path
	end

	private 

	def country_params
		params.require(:country).permit(:name, :flag)
	end
  
  def find_country
		@country = Country.find(params[:id])
	end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

	def index
		@title = 'Beer Collection'
		@beers = Beer.all.limit(6).order('created_at DESC')
	end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

def new
	
end

def create
	@user = User.find_by(username: params[:username])
	#@user = User.where(username: params[:username]).first

	if @user && @user.authenticate(params[:password])
		flash[:notice] = 'Logged in successfully!'
		session[:user_id] = @user.id
		redirect_to root_path
	else
		flash[:error] = 'Incorrect username or password! :\'('
		render :new
	end
end

def destroy
	session.delete(:user_id)
	redirect_to new_session_path
end
  
end

app/controllers/styles_controller.rb
class StylesController < ApplicationController
	before_action :authorize, { only: [:new, :update, :destroy, :edit] }
	before_action :find_style, { only: [:edit, :update, :show, :destroy] }

	def index
		@styles = Style.all.paginate(:page => params[:page], :per_page => 10)
	end

  def new
		@style = Style.new
	end

	def create
		@style = Style.new(style_params)

		if @style.save
			flash[:notice] = 'Style created succesfully :)'
			redirect_to styles_path
		else
			render :new
		end

	end

	def edit
			
	end

	def update		
	  
		if @style.update(style_params)
			redirect_to @style
		else
			render :edit
		end
	end

	def show    
    #@products = @seller.products
  end

	def destroy
	
		@style.destroy
		flash[:notice] = 'Style deleted succesfully'
		redirect_to styles_path
	end

	private 

	def style_params
		params.require(:style).permit(:name, :descriptions)
	end
  
  def find_style
		@style = Style.find(params[:id])
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def new
		@user = User.new
	end

	def create
		@user = User.new(user_params)

		if @user.save
			flash[:notice] = 'Registered successfully!'
			redirect_to root_path
		else
			render :new
		end
	end

	def show
		
	end

	private

	def user_params
		params.require(:user).permit(:username, :password, :password_confirmation)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/beers/_beer.html.erb
<tr>
	<td><center><%= link_to image_tag(beer.image, size: "20x50", alt: "Beer"), beer_path(beer) %></center></td>
	<td><%= link_to beer.name, beer_path(beer) %></td>	
	<td><center><%= beer.quantity %></center></td>	
	<td><center><%= link_to image_tag(beer.country.flag, size: "25x25"), country_path(beer.country_id) %></center></td>
	<td><%= beer.brewery.name %></td>
	<td><center><%= beer.style.name %></center></td>
	<% if logged_in? %>
		<td><%= link_to ' Edit', edit_beer_path(beer), class: 'glyphicon glyphicon-edit btn btn-sm btn-primary' %>
			<%= link_to ' Delete', beer_path(beer), method: :delete, data: {confirm: "Are you sure?"}, class: 'glyphicon glyphicon-trash btn btn-sm btn-danger' %></td>
	<% end %>
</tr>

app/views/beers/_form.html.erb
<%= form_for @beer, html: { multipart: true } do |form| %>	
  <%= form.label :name %>
  <%= form.text_field :name, autofocus: :true, class: 'form-control' %>
  <br>
  <%= form.label :quantity %>
  <%= form.text_field :quantity, class: 'form-control' %>
  <br>
  <%= form.label :country_id %>
  <%= form.collection_select :country_id, Country.all, :id, :name, { prompt: 'Choose country'}, class: 'form-control' %>
  <br>
  <%= form.label :style_id %>
  <%= form.collection_select :style_id, Style.all, :id, :name, { prompt: 'Choose style'}, class: 'form-control' %>
  <br>
  <%= form.label :brewery_id %>
  <%= form.collection_select :brewery_id, Brewery.all, :id, :name, { prompt: 'Choose brewery'}, class: 'form-control' %>
  <br>
  <%= form.label :image %>
  <%= form.text_field :image, class: 'form-control' %>
  <br>
  <%= form.submit params[:action] == 'new' ? 'Save' : 'Update', class: 'btn btn-block btn-default' %>
<% end %>

app/views/beers/edit.html.erb
<div class = "row">
  <div class = "col-md-6 col-md-offset-3">
		<div class="well well-sm well-black">
  		<h1 style="text-align: center";>Update beer</h1>
 			<%= render 'form' %>
 		</div>
 	</div>
</div>

app/views/beers/index.html.erb
	<div class="well well-sm well-bgr"><h3>Beers 
	<% if logged_in? %>
	<%= link_to 'Add new beer', new_beer_path, class: 'btn btn-sm btn-primary' %></h3>
		<% end %>
  </div>
  
  <div class="panel panel-default">  
  		<table class="table">	
				<thead>
					<tr>
						<th></th>
		    		<th>Name</th>
		    		<th><center>Quantity</center></th>
		    		<th><center>Country</center></th>
		    		<th>Brewery</th>
		    		<th><center>Style</center></th>
		    		<% if logged_in? %>
		    <th>Actions</th>
		    <% end %>
					</tr>
				</thead>
				<tbody>
					<%= render @beers.order(name: :asc) %>
				</tbody>
			</table>
<div class="apple_pagination">    
      <div class="top"><%= page_entries_info @beers %></div>

    <center><%= will_paginate @beers %></center>
  </div>

app/views/beers/new.html.erb
<div class = "row">
  <div class = "col-md-6 col-md-offset-3">
  	<div class="well well-sm well-black">
  		<h1 style="text-align: center";>Add new beer</h1>  

   	<%= render 'form' %>

   	</div>
  </div>
</div>

app/views/beers/show.html.erb
<div class="media">
  <div class="media-left">
    <a href="#">
      <%= image_tag(@beer.image, size: "450>x450", alt: "Beer") %>
    </a>
  </div>
  <div class="media-body">
    <div class="panel panel-primary">
      <div class="panel-heading">
        <h3 class="panel-title">Name</h3>
      </div>
      <div class="panel-body">
        <%= @beer.name %>
      </div>
      <div class="panel-heading">
      <h3 class="panel-title">Quantity</h3>
      </div>
      <div class="panel-body">
        <strong><%= @beer.quantity %> </strong>
      </div>
    </div>
  </div>
</div>

app/views/breweries/_beer.html.erb
<div class="panel-heading">Beers <span class="badge"><%= @brewery.beers.count %></span>
</div>
<table class = 'table table-striped table-hover'>
	<thead>
		<tr>
			<th></th>
			<th>Beer</th>
    	<th><center>Quantity</center></th>
    	<% if logged_in? %>
		    <th>Actions</th>
		    <% end %>
		</tr>
	</thead>
	<tbody>
<% @brewery.beers.each do |beer| %>
<tr>
	<td><center><%= link_to image_tag(beer.image, size: "20x50", alt: "Beer"), beer_path(beer) %></center></td>
	<td><%= link_to beer.name, beer_path(beer) %></td>	
	<td><center><%= beer.quantity %></center></td>	
	<% if logged_in? %>
	<td><%= link_to ' Edit', edit_beer_path(beer), class: 'glyphicon glyphicon-edit btn btn-sm btn-primary' %>
			<%= link_to ' Delete', beer_path(beer), method: :delete, data: {confirm: "Are you sure?"}, class: 'glyphicon glyphicon-trash btn btn-sm btn-danger' %></td>
	<% end %>
</tr>
<% end %>
</tbody>
</table>

app/views/breweries/_brewery.html.erb
<tr>
	<td><center><%= link_to image_tag(brewery.image, size: "25x25", alt: "Brewery"), brewery_path(brewery) %></center></td>
	<td><%= link_to brewery.name, brewery_path(brewery) %></td>	
	<td><center><span class="badge"><%= brewery.beers.count %></span></center></td>
	<% if logged_in? %>
		<td><%= link_to ' Edit', edit_brewery_path(brewery), class: 'glyphicon glyphicon-edit btn btn-sm btn-primary' %>
			<%= link_to ' Delete', brewery_path(brewery), method: :delete, data: {confirm: "Are you sure?"}, class: 'glyphicon glyphicon-trash btn btn-sm btn-danger' %></td>
	<% end %>
</tr>

app/views/breweries/_form.html.erb
<%= form_for @brewery do |form|%>	
  <%= form.label :name %>
  <%= form.text_field :name, autofocus: :true, class: 'form-control' %>
  <br>  
  <%= form.label :image %>
  <%= form.text_field :image, class: 'form-control' %>
  <br>
  <%= form.submit params[:action] == 'new' ? 'Save' : 'Update', class: 'btn btn-block btn-default' %>
<% end %>

app/views/breweries/edit.html.erb
<div class = "row">
  <div class = "col-md-6 col-md-offset-3">   
  	<div class="well well-sm well-black">
  		<h1 style="text-align: center";>Update brewery</h1>  
	  	<%= render 'form' %>
	  </div>
  </div>
</div>

app/views/breweries/index.html.erb
	<div class="well well-sm well-bgr"><h3>Breweries 
	<% if logged_in? %>
	<%= link_to 'Add new brewery', new_brewery_path, class: 'btn btn-sm btn-primary' %></h3>
		<% end %>
  </div>
  
  <div class="panel panel-default">  
  	<table class="table table-hover table-striped">	
			<thead>
				<tr>
					<th></th>
		    	<th>Brewery</th>
		    	<th><center>Total Beers</center></th>
		    	<% if logged_in? %>
		    		<th>Actions</th>
		    	<% end %>
				</tr>
			</thead>
			<tbody>
				<%= render @breweries.order(name: :asc) %>
			</tbody>
		</table>
		<div class="apple_pagination">  
			<div class="top"><%= page_entries_info @breweries %></div> 
    	<center><%= will_paginate @breweries %></center>
  	</div>
  </div>

app/views/breweries/new.html.erb
<div class = "row">
  <div class = "col-md-6 col-md-offset-3">
  	<div class="well well-sm well-black">
  		<h1 style="text-align: center";>Add new brewery</h1>  
			<%= render 'form' %>
   	</div>
  </div>
</div>

app/views/breweries/show.html.erb
<div class="media">
  <div class="media-left">
    <a href="#">
      <%= image_tag(@brewery.image, size: "350x350", alt: "Brewery") %>
    </a>
  </div>
  <div class="media-body">
    <div class="panel panel-primary">
      <div class="panel-heading">
        <h3 class="panel-title">Brewery</h3>
      </div>
      <div class="panel-body">
        <%= @brewery.name %>
      </div>
      <%= render 'beer' %>
    </div>
  </div>
</div>

app/views/countries/_beer.html.erb
<table class = 'table table-striped table-hover'>
	<thead>
		<tr>
			<th></th>
			<th>Beer</th>
    	<th><center>Quantity</center></th>
    	<% if logged_in? %>
		    <th>Actions</th>
		    <% end %>
		</tr>
	</thead>
	<tbody>
<% @country.beers.each do |beer| %>
<tr>
	<td><center><%= link_to image_tag(beer.image, size: "20x50", alt: "Beer"), beer_path(beer) %></center></td>
	<td><%= link_to beer.name, beer_path(beer) %></td>	
	<td><center><%= beer.quantity %></center></td>	
	<% if logged_in? %>
	<td><%= link_to ' Edit', edit_beer_path(beer), class: 'glyphicon glyphicon-edit btn btn-sm btn-primary' %>
			<%= link_to ' Delete', beer_path(beer), method: :delete, data: {confirm: "Are you sure?"}, class: 'glyphicon glyphicon-trash btn btn-sm btn-danger' %></td>
			<% end %>
</tr>
<% end %>
</tbody>
</table>

app/views/countries/_country.html.erb
<tr>
	<td><center><%= link_to image_tag(country.flag, size: "25x25", alt: "Flag"), country_path(country) %></center></td>
	<td><%= link_to country.name, country_path(country) %></td>	
	<td><center><span class="badge"><%= country.beers.count %></span></center></td>
	<% if logged_in? %>
		<td><%= link_to ' Edit', edit_country_path(country), class: 'glyphicon glyphicon-edit btn btn-sm btn-primary' %>
			<%= link_to ' Delete', country_path(country), method: :delete, data: {confirm: "Are you sure?"}, class: 'glyphicon glyphicon-trash btn btn-sm btn-danger' %></td>
	<% end %>
</tr>

app/views/countries/_form.html.erb
<%= form_for @country, html: { multipart: true } do |form|%>	
	<%= form.label :name %>
  <%= form.text_field :name, autofocus: :true, class: 'form-control' %>
  <br>
  <%= form.label :flag %>
  <%= form.text_field :flag, class: 'form-control' %>
  <br>
  <%= form.submit params[:action] == 'new' ? 'Save' : 'Update', class: 'btn btn-block btn-default' %>
<% end %>

app/views/countries/edit.html.erb
<div class = "row">
  <div class = "col-md-6 col-md-offset-3">   
  	<div class="well well-sm well-black">
  		<h1 style="text-align: center";>Update country</h1>
  
	  <%= render 'form' %>

	  </div>
  </div>
</div>

app/views/countries/index.html.erb
<div class="well well-sm well-bgr"><h3>Countries 
<% if logged_in? %>
<%= link_to 'Add new country', new_country_path, class: 'btn btn-sm btn-primary' %>
	<% end %>
</h3>
		
  </div>
  
  <div class="panel panel-default">   
  		<table class="table table-hover table-striped">	
				<thead>
					<tr>
						<th></th>
		    		<th>Name</th>
		    		<th><center>Total Beers</center></th>
		    		<% if logged_in? %>
		    <th>Actions</th>
		    <% end %>
					</tr>
				</thead>
				<tbody>
					<%= render @countries.order(name: :asc) %>
				</tbody>
			</table>
<div class="apple_pagination">  
		<div class="top"><%= page_entries_info @countries %></div>  
    <center><%= will_paginate @countries %></center>
  </div>

app/views/countries/new.html.erb
<div class = "row">
  <div class = "col-md-6 col-md-offset-3">
  	<div class="well well-sm well-black">
  		<h1 style="text-align: center";>Add new country</h1>  

   	<%= render 'form' %>

   	</div>
  </div>
</div>

app/views/countries/show.html.erb
<div class="media">
  <div class="media-left">
    <a href="#">
      <%= image_tag(@country.flag, size: "260x260", alt: "Flag") %>
    </a>
  </div>
  <div class="media-body">
    <div class="panel panel-primary">
      <div class="panel-heading">
        <h3 class="panel-title">Name</h3>
      </div>
      <div class="panel-body">
        <%= @country.name %>
      </div>
      <div class="panel-heading">
        <h3 class="panel-title">Beers <span class="badge"><%= @country.beers.count %></span></h3>
      </div>
      <div class="panel-body">
        <%= render 'beer' %>
      </div>
    </div>
  </div>
</div>

app/views/home/_beer.html.erb
<% @beers.each do |beer| %>
	<td><%= link_to image_tag(beer.image, size: "200x200>", alt: "Beer"), beer_path(beer) %></td>
<% end %>

app/views/home/index.html.erb
<div class="panel panel-custom-show">
  <div class="panel-heading"><strong><center><h1><%= @title %></h1></center></strong></div>
  </div>
<div class="panel panel-custom-show">
  <div class="panel-heading"><strong><center>Recently added</center></strong></div>
	<table class="table table-responsive">

		<tbody>
			<%= render 'beer' %>
		</tbody>
	</table>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>My Beer Collection</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<div class = "container">
	  	<%= render 'shared/header' %>
	    <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_header.html.erb
<nav class="navbar navbar-default">
  	<ul class="nav navbar-nav">
      <a><%= link_to "BEER COLLECTION", root_path , class: 'navbar-brand' %></a>
      <li><%= link_to "Beers", beers_path %></li>
      <li><%= link_to "Breweries", breweries_path %></li>
      <li><%= link_to "Countries", countries_path %></li>
      <li><%= link_to "Styles", styles_path %></li>

      <% if logged_in? %>
      	<li><%= link_to session_path, method: :delete do %>
            <i span class="glyphicon glyphicon-log-out"></i> Logout
          <% end %>
          </li>
      <% else %>
      	<li><%= link_to 'Login', new_session_path %></li>
      <% end %>
    </ul> 
  </nav> 

app/views/styles/_beer.html.erb
<div class="panel-heading">Beers <span class="badge"><%= @style.beers.count %></span>
</div>
<table class = 'table table-striped table-hover'>
	<thead>
		<tr>
			<th></th>
			<th>Beer</th>
    	<th><center>Quantity</center></th>
    	<% if logged_in? %>
		    <th>Actions</th>
		    <% end %>
		</tr>
	</thead>
	<tbody>
<% @style.beers.each do |beer| %>
<tr>
	<td><center><%= link_to image_tag(beer.image, size: "20x50", alt: "Beer"), beer_path(beer) %></center></td>
	<td><%= link_to beer.name, beer_path(beer) %></td>	
	<td><center><%= beer.quantity %></center></td>	
	<% if logged_in? %>
	<td><%= link_to ' Edit', edit_beer_path(beer), class: 'glyphicon glyphicon-edit btn btn-sm btn-primary' %>
			<%= link_to ' Delete', beer_path(beer), method: :delete, data: {confirm: "Are you sure?"}, class: 'glyphicon glyphicon-trash btn btn-sm btn-danger' %></td>
			<% end %>
</tr>
<% end %>
</tbody>
</table>

app/views/styles/_form.html.erb
<%= form_for @style do |form|%>	
  <%= form.label :name %>
  <%= form.text_field :name, autofocus: :true, class: 'form-control' %>
  <br>
 	<%= form.label :descriptions, 'Description (optional)' %>
  <%= form.text_area :descriptions, class: 'form-control' %>
  <br>
  <%= form.submit params[:action] == 'new' ? 'Save' : 'Update', class: 'btn btn-block btn-default' %>
<% end %>

app/views/styles/_style.html.erb
<tr>
	<td><%= link_to style.name, style_path(style) %></td>	
	<td><center><span class="badge"><%= style.beers.count %></span></center></td>
	<% if logged_in? %>
		<td><%= link_to ' Edit', edit_style_path(style), class: 'glyphicon glyphicon-edit btn btn-sm btn-primary' %>
			<%= link_to ' Delete', style_path(style), method: :delete, data: {confirm: "Are you sure?"}, class: 'glyphicon glyphicon-trash btn btn-sm btn-danger' %></td>
	<% end %>
</tr>

app/views/styles/edit.html.erb
<div class = "row">
  <div class = "col-md-4 col-md-offset-4">   
  	<div class="well well-sm well-black">
  		<h1 style="text-align: center";>Update style</h1>
  
	  <%= render 'form' %>

	  </div>
  </div>
</div>

app/views/styles/index.html.erb
<div class="well well-sm well-bgr"><h3>Styles 
<% if logged_in? %>
<%= link_to 'Add new style', new_style_path, class: 'btn btn-sm btn-primary' %></h3>
<% end %>
</div>
<div class="panel panel-default">  

  <table class="table table-hover table-striped">	
		<thead>
			<tr>
		    <th>Name</th>
		    <th><center>Total Beers</center></th>
		    <% if logged_in? %>
		    <th>Actions</th>
		    <% end %>
			</tr>
		</thead>
		<tbody>
			<%= render @styles.order(name: :asc) %>
		</tbody>
	</table>
	<div class="apple_pagination">  
		<div class="top"><%= page_entries_info @styles %></div>   
    <center><%= will_paginate @styles %></center>
  </div>
</div>

app/views/styles/new.html.erb
<div class = "row">
  <div class = "col-md-4 col-md-offset-4">
  	<div class="well well-sm well-black">
  		<h1 style="text-align: center";>Add new style</h1>  

   	<%= render 'form' %>

   	</div>
  </div>
</div>

app/views/styles/show.html.erb
<div class="panel panel-primary" style="width: 100%">
  <div class="panel-heading">
    <h3 class="panel-title">Style</h3>
  </div>
  <div class="panel-body">
    <%= @style.name %>
  </div>
  <div class="panel-heading">
    <h3 class="panel-title">Description</h3>
  </div>
  <div class="panel-body">
    <%= @style.descriptions %>
  </div>
  <%= render 'beer' %>
</div>